<template>
  <main class="w-full h-full bg-none relative bg-black/30 flex justify-center items-center">
    <div class="loadingio-spinner-ripple-hwlvii1fnr">
      <div class="ldio-uwo19ydi4ng">
        <div></div>
        <div></div>
      </div>
    </div>
  </main>
</template>
<script lang="ts" setup></script>
<style lang="scss" scoped>
@keyframes ldio-uwo19ydi4ng {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}
.ldio-uwo19ydi4ng div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-uwo19ydi4ng 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.ldio-uwo19ydi4ng div:nth-child(1) {
  border-color: #e90c59;
  animation-delay: 0s;
}
.ldio-uwo19ydi4ng div:nth-child(2) {
  border-color: #46dff0;
  animation-delay: -0.5s;
}
.loadingio-spinner-ripple-hwlvii1fnr {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-uwo19ydi4ng {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-uwo19ydi4ng div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
