name: 部署 koa_ts_server_full doc

on:
  #触发事件，当收到推送的时候执行
  push

jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - name: Checkout Code
        # 使用别人的action
        uses: actions/checkout@v3
      # 步骤名称
      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # node版本

      - name: npm install
        # 步骤执行指令
        run: npm install
        #working-directory此命令的运行目录
        working-directory: ./doc

      - name: build
        #执行build命令，根据个人情况修改，如有多种配置可以改成build:prod,build:dev
        run: npm run build
        working-directory: ./doc

      - name: Deploy
        # uses: peaceiris/actions-gh-pages@v3
        # with:
        #   github_token: ${{ secrets.TOKEN }}
        #   publish_dir: ./public
        run:
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_REPOSITORY: koa_ts_server_full
